/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.rtcapi;

public enum eCALLBACK_TYPE {
  CB_ACC_STATUS,
  CB_CALL_STATUS,
  CB_MSG_STATUS,
  CB_RTC_LOG;

  public final int swigValue() {
    return swigValue;
  }

  public static eCALLBACK_TYPE swigToEnum(int swigValue) {
    eCALLBACK_TYPE[] swigValues = eCALLBACK_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eCALLBACK_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eCALLBACK_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eCALLBACK_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eCALLBACK_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eCALLBACK_TYPE(eCALLBACK_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

