/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.rtcapi;

public enum eNETRTC_CONNECTION_MODE {
  ACC_CONNECTION_MODE_IDLE(rtcapijJNI.ACC_CONNECTION_MODE_IDLE_get()),
  ACC_CONNECTION_MODE_AUTO,
  ACC_CONNECTION_MODE_UDP,
  ACC_CONNECTION_MODE_TUNNEL,
  ACC_CONNECTION_MODE_TUNNEL_WITH_INTERNET_PROXY,
  ACC_CONNECTION_MODE_TCP,
  ACC_CONNECTION_MODE_TLS;

  public final int swigValue() {
    return swigValue;
  }

  public static eNETRTC_CONNECTION_MODE swigToEnum(int swigValue) {
    eNETRTC_CONNECTION_MODE[] swigValues = eNETRTC_CONNECTION_MODE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eNETRTC_CONNECTION_MODE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eNETRTC_CONNECTION_MODE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eNETRTC_CONNECTION_MODE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eNETRTC_CONNECTION_MODE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eNETRTC_CONNECTION_MODE(eNETRTC_CONNECTION_MODE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

