/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.rtcapi;

public class NetrtcCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NetrtcCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetrtcCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtcapijJNI.delete_NetrtcCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    rtcapijJNI.NetrtcCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    rtcapijJNI.NetrtcCallback_change_ownership(this, swigCPtr, true);
  }

  public NetrtcCallback() {
    this(rtcapijJNI.new_NetrtcCallback(), true);
    rtcapijJNI.NetrtcCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void netrtcapi_call_callback(long callid, eCALL_STATUS nState, long call_datas) {
    if (getClass() == NetrtcCallback.class) rtcapijJNI.NetrtcCallback_netrtcapi_call_callback(swigCPtr, this, callid, nState.swigValue(), call_datas); else rtcapijJNI.NetrtcCallback_netrtcapi_call_callbackSwigExplicitNetrtcCallback(swigCPtr, this, callid, nState.swigValue(), call_datas);
  }

  public void netrtcapi_acc_callback(String acc_name, eACC_STATUS nState, long acc_datas) {
    if (getClass() == NetrtcCallback.class) rtcapijJNI.NetrtcCallback_netrtcapi_acc_callback(swigCPtr, this, acc_name, nState.swigValue(), acc_datas); else rtcapijJNI.NetrtcCallback_netrtcapi_acc_callbackSwigExplicitNetrtcCallback(swigCPtr, this, acc_name, nState.swigValue(), acc_datas);
  }

}
