/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.rtcapi;

public class rtcapijJNI {
  public final static native int netrtc_TRUE_get();
  public final static native int netrtc_FALSE_get();
  public final static native int netrtc_NULL_get();
  public final static native int NETSS_STATUS_REGISTRATION_SUCCESSFUL_get();
  public final static native int NETSS_STATUS_REGISTRATION_FAILURE_get();
  public final static native int NETSS_STATUS_REGISTRATION_TIMEOUT_get();
  public final static native int NETSS_STATUS_INCOMING_CALL_get();
  public final static native int NETSS_STATUS_CALL_REINVITE_get();
  public final static native int NETSS_STATUS_CALL_NOANSWER_get();
  public final static native int NETSS_STATUS_CALL_PROCEEDING_get();
  public final static native int NETSS_STATUS_CALL_RINGING_get();
  public final static native int NETSS_STATUS_OUTGOING_CALL_ANSWERED_get();
  public final static native int NETSS_STATUS_CALL_REDIRECTED_get();
  public final static native int NETSS_STATUS_CALL_REQUESTFAILURE_get();
  public final static native int NETSS_STATUS_CALL_SERVERFAILURE_get();
  public final static native int NETSS_STATUS_GLOBAL_FAILURE_get();
  public final static native int NETSS_STATUS_CALL_ACK_get();
  public final static native int NETSS_STATUS_CALL_CANCELLED_get();
  public final static native int NETSS_STATUS_CALL_TIMEOUT_get();
  public final static native int NETSS_STATUS_CALL_CLOSED_get();
  public final static native int NETSS_STATUS_CALL_RELEASED_get();
  public final static native int NETSS_STATUS_INFO_MESSAGE_get();
  public final static native int NETSS_STATUS_CALL_MESSAGE_REQUESTFAILURE_get();
  public final static native int NETSS_STATUS_OTHER_SIP_MESSAGE_get();
  public final static native int NETSS_STATUS_CALL_HOLD_ON_get();
  public final static native int NETSS_STATUS_CALL_HOLD_OFF_get();
  public final static native int NETSS_STATUS_CALL_MUTE_get();
  public final static native int NETSS_STATUS_CALL_UNMUTE_get();
  public final static native int NETSS_STATUS_CALL_REFER_TO_get();
  public final static native int NETSS_STATUS_REGISTRATION_ACCOUNT_ERROR_get();
  public final static native int NETSS_STATUS_OPTIONS_MESSAGE_get();
  public final static native int NETSS_STATUS_NOTIFY_MESSAGE_get();
  public final static native int NETSS_STATUS_MESSAGE_MESSAGE_get();
  public final static native int NETSS_STATUS_LOGOUT_TIMEOUT_get();
  public final static native int NETSS_STATUS_LOGOUT_FAILURE_get();
  public final static native int NETSS_STATUS_TIMESTAMP_get();
  public final static native int NETSS_STATUS_INVITE_RESULT_get();
  public final static native int NETSS_STATUS_LOGOUT_get();
  public final static native int NETSS_STATUS_SUBSCRIPT_REQUESTFAILURE_get();
  public final static native int NETSS_STATUS_SUBSCRIPT_NOANSWER_get();
  public final static native int NETSS_STATUS_SUBSCRIPT_ANSWERED_get();
  public final static native int NETSS_STATUS_NOTIFY_OTHERS_get();
  public final static native int NETSS_STATUS_CONNECTED_SUCCESS_get();
  public final static native int NETSS_STATUS_CONNECTED_FAILED_get();
  public final static native int ACC_CONNECTION_MODE_IDLE_get();
  public final static native void netrtc_init(String jarg1, String jarg2);
  public final static native void netrtc_init_done();
  public final static native void netrtc_setcallback(int jarg1, long jarg2);
  public final static native String netrtc_version();
  public final static native String netrtc_log(int jarg1, String jarg2);
  public final static native void netrtc_set_context(String jarg1, Object jarg2);
  public final static native void netrtc_set_context2(String jarg1, long jarg2, Object jarg3);
  public final static native void netrtc_set_config(String jarg1, String jarg2);
  public final static native String netrtc_get_config(String jarg1);
  public final static native String netrtc_get_codeclist();
  public final static native long netrtc_hashmap_init();
  public final static native int netrtc_hashmap_set(long jarg1, String jarg2, String jarg3);
  public final static native long netrtc_hashmap_get(long jarg1, String jarg2);
  public final static native String netrtc_hashmap_getstr(long jarg1, String jarg2);
  public final static native long netrtc_hashmap_first(long jarg1);
  public final static native long netrtc_hashmap_next(long jarg1);
  public final static native String netrtc_hashmap_this_key(long jarg1);
  public final static native long netrtc_hashmap_this_value(long jarg1);
  public final static native long netrtc_hashmap_count(long jarg1);
  public final static native void netrtc_hashmap_clear(long jarg1);
  public final static native void netrtc_hashmap_free(long jarg1);
  public final static native long netrtc_acc_add(String jarg1, String jarg2, String jarg3, long jarg4);
  public final static native int netrtc_acc_count();
  public final static native long netrtc_acc_names(long jarg1, int jarg2);
  public final static native int netrtc_acc_set_config(String jarg1, String jarg2, String jarg3);
  public final static native String netrtc_acc_get_config(String jarg1, String jarg2);
  public final static native long netrtc_acc_get_configs(String jarg1);
  public final static native int netrtc_acc_del(String jarg1);
  public final static native int netrtc_send_subscribe(String jarg1, String jarg2);
  public final static native int netrtc_acc_register(String jarg1);
  public final static native void netrtc_acc_tryconnect(String jarg1);
  public final static native int netrtc_acc_unregister(String jarg1);
  public final static native int netrtc_acc_reset_network(String jarg1);
  public final static native int netrtc_acc_reset_network_cause(String jarg1, String jarg2);
  public final static native int netrtc_acc_get_register_status(String jarg1);
  public final static native int netrtc_acc_get_connect_status(String jarg1);
  public final static native int netrtc_acc_get_connectionmode(String jarg1);
  public final static native String netrtc_call_getsipcallid(long jarg1);
  public final static native String netrtc_call_audio(String jarg1, String jarg2, long jarg3);
  public final static native String netrtc_call_audio_sdp(String jarg1, String jarg2, long jarg3, String jarg4);
  public final static native int netrtc_call_recall(long jarg1);
  public final static native int netrtc_call_recall_sdp(long jarg1, String jarg2);
  public final static native int netrtc_acc_message(String jarg1, String jarg2, String jarg3);
  public final static native String netrtc_call_acc_name(long jarg1);
  public final static native int netrtc_call_hangup(long jarg1);
  public final static native int netrtc_call_hangup_withcode(long jarg1, int jarg2);
  public final static native int netrtc_call_ring_sdp(long jarg1, String jarg2);
  public final static native int netrtc_call_accept(long jarg1);
  public final static native int netrtc_call_accept_sdp(long jarg1, String jarg2);
  public final static native int netrtc_call_reject(long jarg1);
  public final static native int netrtc_call_getstatus(long jarg1);
  public final static native void netrtc_call_senddtmf(long jarg1, char jarg2, int jarg3);
  public final static native void netrtc_call_mutemic(long jarg1, int jarg2);
  public final static native int netrtc_call_quality(long jarg1);
  public final static native int netrtc_call_holdon(long jarg1);
  public final static native int netrtc_call_holdoff(long jarg1);
  public final static native void netrtc_call_setmicVol(long jarg1, int jarg2);
  public final static native int netrtc_call_getmicVol(long jarg1);
  public final static native void netrtc_call_setspkVol(long jarg1, int jarg2);
  public final static native int netrtc_call_getspkVol(long jarg1);
  public final static native int getfileinfo(String jarg1);
  public final static native int convertFile(String jarg1, String jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int netrtc_startRecordingMicrophone(String jarg1);
  public final static native int netrtc_stopRecordingMicrophone();
  public final static native int netrtc_startRecordingPlayout(long jarg1, String jarg2);
  public final static native int netrtc_stopRecordingPlayout(long jarg1);
  public final static native int netrtc_startPlayFileAsMicrophone(long jarg1, String jarg2, int jarg3, int jarg4);
  public final static native int netrtc_stopPlayingFileAsMicrophone(long jarg1);
  public final static native int netrtc_startPlayFileLocally(long jarg1, String jarg2, int jarg3);
  public final static native int netrtc_stopPlayingFileLocally(long jarg1);
  public final static native int netrtc_call_startaudio(long jarg1);
  public final static native int netrtc_call_stopaudio(long jarg1);
  public final static native void logEncrypt(long jarg1);
  public final static native void logFileDecrypt(String jarg1);
  public final static native int c_netrtcapi_acc_callback(String jarg1, int jarg2, long jarg3);
  public final static native int c_netrtcapi_call_callback(long jarg1, int jarg2, long jarg3);
  public final static native long new_NetrtcCallback();
  public final static native void NetrtcCallback_netrtcapi_call_callback(long jarg1, NetrtcCallback jarg1_, long jarg2, int jarg3, long jarg4);
  public final static native void NetrtcCallback_netrtcapi_call_callbackSwigExplicitNetrtcCallback(long jarg1, NetrtcCallback jarg1_, long jarg2, int jarg3, long jarg4);
  public final static native void NetrtcCallback_netrtcapi_acc_callback(long jarg1, NetrtcCallback jarg1_, String jarg2, int jarg3, long jarg4);
  public final static native void NetrtcCallback_netrtcapi_acc_callbackSwigExplicitNetrtcCallback(long jarg1, NetrtcCallback jarg1_, String jarg2, int jarg3, long jarg4);
  public final static native void delete_NetrtcCallback(long jarg1);
  public final static native void NetrtcCallback_director_connect(NetrtcCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void NetrtcCallback_change_ownership(NetrtcCallback obj, long cptr, boolean take_or_release);
  public final static native void registeredCallbackObject_set(long jarg1, NetrtcCallback jarg1_);
  public final static native long registeredCallbackObject_get();
  public final static native void setCallbackObject(long jarg1, NetrtcCallback jarg1_);

  public static void SwigDirector_NetrtcCallback_netrtcapi_call_callback(NetrtcCallback self, long callid, int nState, long call_datas) {
    self.netrtcapi_call_callback(callid, eCALL_STATUS.swigToEnum(nState), call_datas);
  }
  public static void SwigDirector_NetrtcCallback_netrtcapi_acc_callback(NetrtcCallback self, String acc_name, int nState, long acc_datas) {
    self.netrtcapi_acc_callback(acc_name, eACC_STATUS.swigToEnum(nState), acc_datas);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
