name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
## REPLACE
  ## Update your dependencies to use `flutter_web`
  #flutter:
  #  sdk: flutter
  flutter_web: any
  flutter_web_ui: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2
  build_runner: any
  json_serializable: any
#  cached_network_image: ^0.5.0
  dio: any
  date_format: any
  intl: any
#  flutter_webview_plugin: ^0.3.0+2
  crypto: any
#  fluttertoast: ^2.0.9
  flutter_refresh: any
  gbk2utf8: any
#  fluwx: ^0.5.6
#  share: ^0.5.3
#  flutter_html: ^0.8.2
  tuple: any
  date_utils: any
  sticky_headers: "^0.1.7"
#  shared_preferences: ^0.4.0
  qr_flutter: any
#  image_picker: 0.4.12+1
  event_bus: any
#  qr_code_scanner: ^0.0.2
  xml2json: any
#  sqflite: ^1.1.0
#  hf_sdk:
#   path: hf_sdk

dev_dependencies:
  ## REPLACE
   ## Same goes for test packages
   #flutter_test:
   #  sdk: flutter
   #flutter_web_test: any
   ## ADD
   ## Add these dependencies to enable the Dart web build system
   build_runner: any
   build_web_compilers: any

   test: any


## ADD
## flutter_web packages are not published to pub.dartlang.org
## These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
#  assets:
#    - images/cover_img.jpg
#    - images/ic_avatar_default.png
#    - images/ic_arrow_right.png
#    - images/img.jpg
#    - images/lebron.jpg
#    - images/xk.jpg
#    - images/double_ring_loading_io.gif
#    - images/a001.jpg
#    - images/a002.jpg
#    - images/a003.jpg
#    - images/a004.jpg
#    - images/a005.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
