/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public class c_Conversation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected c_Conversation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(c_Conversation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imapijJNI.delete_c_Conversation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIsTopPriority(boolean value) {
    imapijJNI.c_Conversation_isTopPriority_set(swigCPtr, this, value);
  }

  public boolean getIsTopPriority() {
    return imapijJNI.c_Conversation_isTopPriority_get(swigCPtr, this);
  }

  public void setIsGroupChat(boolean value) {
    imapijJNI.c_Conversation_isGroupChat_set(swigCPtr, this, value);
  }

  public boolean getIsGroupChat() {
    return imapijJNI.c_Conversation_isGroupChat_get(swigCPtr, this);
  }

  public void setConversationID(int value) {
    imapijJNI.c_Conversation_conversationID_set(swigCPtr, this, value);
  }

  public int getConversationID() {
    return imapijJNI.c_Conversation_conversationID_get(swigCPtr, this);
  }

  public void setMessageCount(int value) {
    imapijJNI.c_Conversation_messageCount_set(swigCPtr, this, value);
  }

  public int getMessageCount() {
    return imapijJNI.c_Conversation_messageCount_get(swigCPtr, this);
  }

  public void setMessageType(int value) {
    imapijJNI.c_Conversation_messageType_set(swigCPtr, this, value);
  }

  public int getMessageType() {
    return imapijJNI.c_Conversation_messageType_get(swigCPtr, this);
  }

  public void setConversation(String value) {
    imapijJNI.c_Conversation_conversation_set(swigCPtr, this, value);
  }

  public String getConversation() {
    return imapijJNI.c_Conversation_conversation_get(swigCPtr, this);
  }

  public void setConversation_nickname(byte[] value) {
    imapijJNI.c_Conversation_conversation_nickname_set(swigCPtr, this, value);
  }

  public byte[] getConversation_nickname() {
    return imapijJNI.c_Conversation_conversation_nickname_get(swigCPtr, this);
}

  public void setMsg_sender(String value) {
    imapijJNI.c_Conversation_msg_sender_set(swigCPtr, this, value);
  }

  public String getMsg_sender() {
    return imapijJNI.c_Conversation_msg_sender_get(swigCPtr, this);
  }

  public void setMsg_body(byte[] value) {
    imapijJNI.c_Conversation_msg_body_set(swigCPtr, this, value);
  }

  public byte[] getMsg_body() {
    return imapijJNI.c_Conversation_msg_body_get(swigCPtr, this);
}

  public void setDraft(byte[] value) {
    imapijJNI.c_Conversation_draft_set(swigCPtr, this, value);
  }

  public byte[] getDraft() {
    return imapijJNI.c_Conversation_draft_get(swigCPtr, this);
}

  public void setProperties(String value) {
    imapijJNI.c_Conversation_properties_set(swigCPtr, this, value);
  }

  public String getProperties() {
    return imapijJNI.c_Conversation_properties_get(swigCPtr, this);
  }

  public void setMsg_date(String value) {
    imapijJNI.c_Conversation_msg_date_set(swigCPtr, this, value);
  }

  public String getMsg_date() {
    return imapijJNI.c_Conversation_msg_date_get(swigCPtr, this);
  }

  public void setMsg_server_date(String value) {
    imapijJNI.c_Conversation_msg_server_date_set(swigCPtr, this, value);
  }

  public String getMsg_server_date() {
    return imapijJNI.c_Conversation_msg_server_date_get(swigCPtr, this);
  }

  public void setChair_man(String value) {
    imapijJNI.c_Conversation_chair_man_set(swigCPtr, this, value);
  }

  public String getChair_man() {
    return imapijJNI.c_Conversation_chair_man_get(swigCPtr, this);
  }

  public void setMsg_status(int value) {
    imapijJNI.c_Conversation_msg_status_set(swigCPtr, this, value);
  }

  public int getMsg_status() {
    return imapijJNI.c_Conversation_msg_status_get(swigCPtr, this);
  }

  public void setMessageID(int value) {
    imapijJNI.c_Conversation_messageID_set(swigCPtr, this, value);
  }

  public int getMessageID() {
    return imapijJNI.c_Conversation_messageID_get(swigCPtr, this);
  }

  public void setUnreadMessageCount(int value) {
    imapijJNI.c_Conversation_unreadMessageCount_set(swigCPtr, this, value);
  }

  public int getUnreadMessageCount() {
    return imapijJNI.c_Conversation_unreadMessageCount_get(swigCPtr, this);
  }

  public c_Conversation() {
    this(imapijJNI.new_c_Conversation(), true);
  }

}
