/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public class c_Group {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected c_Group(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(c_Group obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imapijJNI.delete_c_Group(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGroup_name(String value) {
    imapijJNI.c_Group_group_name_set(swigCPtr, this, value);
  }

  public String getGroup_name() {
    return imapijJNI.c_Group_group_name_get(swigCPtr, this);
  }

  public void setGroup_nickname(byte[] value) {
    imapijJNI.c_Group_group_nickname_set(swigCPtr, this, value);
  }

  public byte[] getGroup_nickname() {
    return imapijJNI.c_Group_group_nickname_get(swigCPtr, this);
}

  public void setGroup_creator(String value) {
    imapijJNI.c_Group_group_creator_set(swigCPtr, this, value);
  }

  public String getGroup_creator() {
    return imapijJNI.c_Group_group_creator_get(swigCPtr, this);
  }

  public c_Group() {
    this(imapijJNI.new_c_Group(), true);
  }

}
