/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public class c_GroupMember {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected c_GroupMember(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(c_GroupMember obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imapijJNI.delete_c_GroupMember(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGroupName(String value) {
    imapijJNI.c_GroupMember_groupName_set(swigCPtr, this, value);
  }

  public String getGroupName() {
    return imapijJNI.c_GroupMember_groupName_get(swigCPtr, this);
  }

  public void setMemberName(String value) {
    imapijJNI.c_GroupMember_memberName_set(swigCPtr, this, value);
  }

  public String getMemberName() {
    return imapijJNI.c_GroupMember_memberName_get(swigCPtr, this);
  }

  public void setNickname(byte[] value) {
    imapijJNI.c_GroupMember_nickname_set(swigCPtr, this, value);
  }

  public byte[] getNickname() {
    return imapijJNI.c_GroupMember_nickname_get(swigCPtr, this);
}

  public void setRole(int value) {
    imapijJNI.c_GroupMember_role_set(swigCPtr, this, value);
  }

  public int getRole() {
    return imapijJNI.c_GroupMember_role_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    imapijJNI.c_GroupMember_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return imapijJNI.c_GroupMember_status_get(swigCPtr, this);
  }

  public c_GroupMember() {
    this(imapijJNI.new_c_GroupMember(), true);
  }

}
