/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public class c_Message {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected c_Message(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(c_Message obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imapijJNI.delete_c_Message(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsg_status(int value) {
    imapijJNI.c_Message_msg_status_set(swigCPtr, this, value);
  }

  public int getMsg_status() {
    return imapijJNI.c_Message_msg_status_get(swigCPtr, this);
  }

  public void setIsRead(int value) {
    imapijJNI.c_Message_isRead_set(swigCPtr, this, value);
  }

  public int getIsRead() {
    return imapijJNI.c_Message_isRead_get(swigCPtr, this);
  }

  public void setMessageID(int value) {
    imapijJNI.c_Message_messageID_set(swigCPtr, this, value);
  }

  public int getMessageID() {
    return imapijJNI.c_Message_messageID_get(swigCPtr, this);
  }

  public void setMessageType(int value) {
    imapijJNI.c_Message_messageType_set(swigCPtr, this, value);
  }

  public int getMessageType() {
    return imapijJNI.c_Message_messageType_get(swigCPtr, this);
  }

  public void setConversationID(int value) {
    imapijJNI.c_Message_conversationID_set(swigCPtr, this, value);
  }

  public int getConversationID() {
    return imapijJNI.c_Message_conversationID_get(swigCPtr, this);
  }

  public void setMsg_sender(String value) {
    imapijJNI.c_Message_msg_sender_set(swigCPtr, this, value);
  }

  public String getMsg_sender() {
    return imapijJNI.c_Message_msg_sender_get(swigCPtr, this);
  }

  public void setMsg_receiver(String value) {
    imapijJNI.c_Message_msg_receiver_set(swigCPtr, this, value);
  }

  public String getMsg_receiver() {
    return imapijJNI.c_Message_msg_receiver_get(swigCPtr, this);
  }

  public void setMsg_body(byte[] value) {
    imapijJNI.c_Message_msg_body_set(swigCPtr, this, value);
  }

  public byte[] getMsg_body() {
    return imapijJNI.c_Message_msg_body_get(swigCPtr, this);
}

  public void setMsg_date(String value) {
    imapijJNI.c_Message_msg_date_set(swigCPtr, this, value);
  }

  public String getMsg_date() {
    return imapijJNI.c_Message_msg_date_get(swigCPtr, this);
  }

  public void setLocal_resource(String value) {
    imapijJNI.c_Message_local_resource_set(swigCPtr, this, value);
  }

  public String getLocal_resource() {
    return imapijJNI.c_Message_local_resource_get(swigCPtr, this);
  }

  public void setFileURL(String value) {
    imapijJNI.c_Message_fileURL_set(swigCPtr, this, value);
  }

  public String getFileURL() {
    return imapijJNI.c_Message_fileURL_get(swigCPtr, this);
  }

  public void setFileTotalSize(int value) {
    imapijJNI.c_Message_fileTotalSize_set(swigCPtr, this, value);
  }

  public int getFileTotalSize() {
    return imapijJNI.c_Message_fileTotalSize_get(swigCPtr, this);
  }

  public void setFileCurSize(int value) {
    imapijJNI.c_Message_fileCurSize_set(swigCPtr, this, value);
  }

  public int getFileCurSize() {
    return imapijJNI.c_Message_fileCurSize_get(swigCPtr, this);
  }

  public void setChatType(int value) {
    imapijJNI.c_Message_chatType_set(swigCPtr, this, value);
  }

  public int getChatType() {
    return imapijJNI.c_Message_chatType_get(swigCPtr, this);
  }

  public void setMsg_server_date(String value) {
    imapijJNI.c_Message_msg_server_date_set(swigCPtr, this, value);
  }

  public String getMsg_server_date() {
    return imapijJNI.c_Message_msg_server_date_get(swigCPtr, this);
  }

  public void setError_info(String value) {
    imapijJNI.c_Message_error_info_set(swigCPtr, this, value);
  }

  public String getError_info() {
    return imapijJNI.c_Message_error_info_get(swigCPtr, this);
  }

  public c_Message() {
    this(imapijJNI.new_c_Message(), true);
  }

}
