/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public enum eConversationEvent {
  CONV_CONFIG_UPDATE_EVENT;

  public final int swigValue() {
    return swigValue;
  }

  public static eConversationEvent swigToEnum(int swigValue) {
    eConversationEvent[] swigValues = eConversationEvent.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eConversationEvent swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eConversationEvent.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eConversationEvent() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eConversationEvent(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eConversationEvent(eConversationEvent swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

