/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public enum eIMCALLBACK_TYPE {
  CB_MSG_RECV,
  CB_MSG_STATUS_CHANGED,
  CB_SOCK_ERROR,
  CB_PING_OUT,
  CB_PRESENCE_SYNC,
  CB_FRIEND_SUBSCRIBE,
  CB_FRIEND_UNSUBSCRIBED,
  CB_VCARD_RECV,
  CB_MUC_EVENT,
  CB_FILE_TRANSFER,
  CB_BROADCAST_RECV,
  CB_HISTORY_EVENT,
  CB_CONVERSATION_EVENT;

  public final int swigValue() {
    return swigValue;
  }

  public static eIMCALLBACK_TYPE swigToEnum(int swigValue) {
    eIMCALLBACK_TYPE[] swigValues = eIMCALLBACK_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eIMCALLBACK_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eIMCALLBACK_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eIMCALLBACK_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eIMCALLBACK_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eIMCALLBACK_TYPE(eIMCALLBACK_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

