/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public enum eMessageStatus {
  C_MESSAGE_STATUS_MESSAGE_CREATE,
  C_MESSAGE_STATUS_MESSAGE_SEND_FAILED,
  C_MESSAGE_STATUS_MESSAGE_WAIT_RECEIVER,
  C_MESSAGE_STATUS_MESSAGE_SUCCESS,
  C_MESSAGE_STATUS_FILE_CREATE,
  C_MESSAGE_STATUS_FILE_URL_FAILED,
  C_MESSAGE_STATUS_FILE_SEND_FAILED,
  C_MESSAGE_STATUS_FILE_SEND_OK,
  C_MESSAGE_STATUS_FILE_PROGRESSING,
  C_MESSAGE_STATUS_FILE_RECV_CREATE,
  C_MESSAGE_STATUS_FILE_RECV_FAILED,
  C_MESSAGE_STATUS_FAILED,
  C_MESSAGE_STATUS_READ;

  public final int swigValue() {
    return swigValue;
  }

  public static eMessageStatus swigToEnum(int swigValue) {
    eMessageStatus[] swigValues = eMessageStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eMessageStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eMessageStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eMessageStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eMessageStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eMessageStatus(eMessageStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

