/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public enum eMucEvent {
  MUC_MEMBER_INIT,
  MUC_MEMBER_UPDATE,
  MUC_INVITE_RECV,
  MUC_JOIN_EVENT,
  MUC_INVITE_SUCCESS,
  MUC_CONFIG_UPDATE_EVENT;

  public final int swigValue() {
    return swigValue;
  }

  public static eMucEvent swigToEnum(int swigValue) {
    eMucEvent[] swigValues = eMucEvent.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eMucEvent swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eMucEvent.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eMucEvent() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eMucEvent(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eMucEvent(eMucEvent swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

