/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public enum eShow {
  SHOW_NONE(imapijJNI.SHOW_NONE_get()),
  SHOW_OFFLINE(imapijJNI.SHOW_OFFLINE_get()),
  SHOW_XA(imapijJNI.SHOW_XA_get()),
  SHOW_AWAY(imapijJNI.SHOW_AWAY_get()),
  SHOW_DND(imapijJNI.SHOW_DND_get()),
  SHOW_ONLINE(imapijJNI.SHOW_ONLINE_get()),
  SHOW_CHAT(imapijJNI.SHOW_CHAT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static eShow swigToEnum(int swigValue) {
    eShow[] swigValues = eShow.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (eShow swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + eShow.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private eShow() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private eShow(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private eShow(eShow swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

