/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ultralinked.voip.imapi;

public class FriendInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FriendInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FriendInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imapijJNI.delete_FriendInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFriend_name(String value) {
    imapijJNI.FriendInfo_friend_name_set(swigCPtr, this, value);
  }

  public String getFriend_name() {
    return imapijJNI.FriendInfo_friend_name_get(swigCPtr, this);
  }

  public void setFriend_nickname(byte[] value) {
    imapijJNI.FriendInfo_friend_nickname_set(swigCPtr, this, value);
  }

  public byte[] getFriend_nickname() {
    return imapijJNI.FriendInfo_friend_nickname_get(swigCPtr, this);
}

  public void setFriend_show(eShow value) {
    imapijJNI.FriendInfo_friend_show_set(swigCPtr, this, value.swigValue());
  }

  public eShow getFriend_show() {
    return eShow.swigToEnum(imapijJNI.FriendInfo_friend_show_get(swigCPtr, this));
  }

  public void setFriend_status(byte[] value) {
    imapijJNI.FriendInfo_friend_status_set(swigCPtr, this, value);
  }

  public byte[] getFriend_status() {
    return imapijJNI.FriendInfo_friend_status_get(swigCPtr, this);
}

  public FriendInfo() {
    this(imapijJNI.new_FriendInfo(), true);
  }

}
